src/Application/SchoolBundle/Entity/ClassGroup.php
<?php

namespace Application\SchoolBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ClassGroup
 */
class ClassGroup
{
    /**
     * @var integer
     */
    private $grade;

    /**
     * @var string
     */
    private $alphabet;

    /**
     * @var integer
     */
    private $id;

    /**
     * @var \Application\SchoolBundle\Entity\Personal
     */
    private $personal;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->students = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set grade
     *
     * @param integer $grade
     * @return ClassGroup
     */
    public function setGrade($grade)
    {
        $this->grade = $grade;

        return $this;
    }

    /**
     * Get grade
     *
     * @return integer
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     * Set alphabet
     *
     * @param string $alphabet
     * @return ClassGroup
     */
    public function setAlphabet($alphabet)
    {
        $this->alphabet = $alphabet;

        return $this;
    }

    /**
     * Get alphabet
     *
     * @return string
     */
    public function getAlphabet()
    {
        return $this->alphabet;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set personal
     *
     * @param \Application\SchoolBundle\Entity\Personal $personal
     * @return ClassGroup
     */
    public function setPersonal(\Application\SchoolBundle\Entity\Personal $personal = null)
    {
        $this->personal = $personal;

        return $this;
    }

    /**
     * Get personal
     *
     * @return \Application\SchoolBundle\Entity\Personal
     */
    public function getPersonal()
    {
        return $this->personal;
    }

    public function __toString()
    {
        return $this->getGrade() . '-' . $this->getAlphabet();
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $students;


    /**
     * Add students
     *
     * @param \Application\SchoolBundle\Entity\Student $students
     * @return ClassGroup
     */
    public function addStudent(\Application\SchoolBundle\Entity\Student $students)
    {
        $this->students[] = $students;

        return $this;
    }

    /**
     * Remove students
     *
     * @param \Application\SchoolBundle\Entity\Student $students
     */
    public function removeStudent(\Application\SchoolBundle\Entity\Student $students)
    {
        $this->students->removeElement($students);
    }

    /**
     * Get students
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStudents()
    {
        return $this->students;
    }

    public function getStudentsByEnd()
    {
        $count = 0;
        foreach ($this->students as $student) {
            if (is_object($student->getTransfer()) && $student->getTransfer()->getMoved() == 'Выбыл') {
                $count++;
            }
        }

        return $this->students->count() - $count;
    }

    public function getGenderCount()
    {
        $count = array('m' => 0, 'f' => 0);
        foreach ($this->students as $s) {
            $count['m'] += ($s->getSex() === 'М');
            $count['f'] += ($s->getSex() === 'Ж');
        }

        return $count;
    }

    public function getFull()
    {
        return $this->getGrade() . '-' . $this->getAlphabet();
    }

    /**
     * @var boolean
     */
    private $active;


    /**
     * Set active
     *
     * @param boolean $active
     * @return ClassGroup
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive()
    {
        return $this->active;
    }
}

src/Application/SchoolBundle/Entity/Report.php
<?php

namespace Application\SchoolBundle\Entity;

use Application\SchoolBundle\Entity\AcademicYear;
use Application\SchoolBundle\Entity\Quarter;
use Application\SchoolBundle\Entity\ReportClass;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Report
 */
class Report
{

    /**
     * @var integer
     */
    private $id;

    /**
     * @var AcademicYear
     */
    private $academicYear;

    /**
     * @var Quarter
     */
    private $quarter;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set academicYear
     *
     * @param AcademicYear $academicYear
     * @return Report
     */
    public function setAcademicYear(AcademicYear $academicYear = null)
    {
        $this->academicYear = $academicYear;

        return $this;
    }

    /**
     * Get academicYear
     *
     * @return AcademicYear
     */
    public function getAcademicYear()
    {
        return $this->academicYear;
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $students;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->students = new ArrayCollection();
    }


    /**
     * Set quarter
     *
     * @param Quarter $quarter
     * @return Report
     */
    public function setQuarter(Quarter $quarter = null)
    {
        $this->quarter = $quarter;

        return $this;
    }

    /**
     * Get quarter
     *
     * @return Quarter
     */
    public function getQuarter()
    {
        return $this->quarter;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $reportClass;


    /**
     * Add reportClass
     *
     * @param ReportClass $reportClass
     * @return Report
     */
    public function addReportClass(ReportClass $reportClass)
    {
        $this->reportClass[] = $reportClass;

        return $this;
    }

    /**
     * Remove reportClass
     *
     * @param ReportClass $reportClass
     */
    public function removeReportClass(ReportClass $reportClass)
    {
        $this->reportClass->removeElement($reportClass);
    }

    /**
     * Get reportClass
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getReportClass()
    {
        return $this->reportClass;
    }
}

src/Application/SchoolBundle/Form/ReportType.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/3/14
 * Time: 2:53 PM
 */

namespace Application\SchoolBundle\Form;


use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class ReportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('academicYear', 'entity', array(
            'class' => 'Application\SchoolBundle\Entity\AcademicYear',
            'property' => 'year',
            'query_builder' => function (EntityRepository $entityRepository) {
                    return $entityRepository->createQueryBuilder('a')
                        ->orderBy('a.year', 'desc');
                }
        ))
            ->add('quarter', 'entity', array(
                'class' => 'Application\SchoolBundle\Entity\Report',
                'query_builder' => function (EntityRepository $entityRepository) {
                        return $entityRepository->createQueryBuilder('r')
                            ->groupBy('r.academicYear')
                            ->orderBy('r.academicYear', 'desc');
                    },
                'property' => 'quarter'
            ));
    }


    public function getName()
    {
        return "report";
    }
}

src/Application/SchoolBundle/Controller/ReportController.php
<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 02.04.14
 * Time: 14:11
 */

namespace Application\SchoolBundle\Controller;


use Application\SchoolBundle\Entity\Report;
use Application\SchoolBundle\Form\ReportType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;

class ReportController extends Controller
{

    public function indexAction()
    {
        return $this->render('ApplicationSchoolBundle:Report:index.html.twig');
    }

    public function createAction()
    {
        return $this->render('ApplicationSchoolBundle:Report:create.html.twig');
    }

    public function addToHistoryAction()
    {
        $em = $this->getDoctrine()->getManager();

        $school = $em->getRepository('ApplicationSchoolBundle:School')->findAll()[0];

        $students = $em->getRepository('ApplicationSchoolBundle:Student')->findAll();

        $em->getRepository('ApplicationSchoolBundle:ClassGroup')->persist();


        $result = $em->getRepository('ApplicationSchoolBundle:Report')->persist($school, $students);

        return new JsonResponse($result);
    }

    public function searchFormAction()
    {
        $report = new Report();

        $reportForm = $this->createForm(new ReportType(), $report);

        return $this->render(
            'ApplicationSchoolBundle:Report:form.html.twig',
            array('form' => $reportForm->createView())
        );
    }


} 

src/Application/SchoolBundle/Resources/views/Report/classgroup.html.twig
{% extends 'ApplicationSchoolBundle::layout.html.twig' %}
{% block content %}
    {% set students = classgroup.students %}
    <h2 class="text-center">Отчет</h2>

    <p>Класс <strong>{{ classgroup.grade }} "{{ classgroup.alphabet }}"</strong></p>
    <p>Классный руководитель <strong>{{ classgroup.personal }}</strong></p>

    <p class="text-danger">На начало года (?) {#TODO: create column in table#}</p>

    <p class="text-danger">На начало четверти: (?){#TODO:   calculate#}</p>

    <p>На конец четверти: <strong>{{ classgroup.studentsByEnd }}</strong></p>

    <p>Выбыло</p>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Ф.И.О</th>
            <th>Число</th>
            <th>Куда</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            {% if student.transfer != NULL and student.transfer.moved =='Выбыл' %}
                <tr>
                    <td>
                        {{ student.firstname }} {{ student.lastname }}
                    </td>
                    <td>{{ student.transfer.date|date('d-m-Y') }}</td>
                    <td>{{ student.transfer }} {{ student.transfer.classGroup }}</td>
                    <td>{{ student.transfer.transferlocation }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    <p>Прибыло</p>

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Ф.И.О</th>
            <th>Число</th>
            <th>Куда</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            {% if student.transfer != NULL and student.transfer.moved =='Прибыл' %}
                <tr>
                    <td>
                        {{ student.firstname }} {{ student.lastname }}
                    </td>
                    <td>{{ student.transfer.date|date('d-m-Y') }}</td>
                    <td>{{ student.transfer }} {{ student.transfer.classGroup }}</td>
                    <td>{{ student.transfer.transferlocation }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>


    <section>
        <p>По годам</p>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Год</th>
                {% for year in byYear %}
                    <th>{{ year.y }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>мальчики</td>
                {% for year in byYear %}
                    <td>{{ year.male }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td>девочки</td>
                {% for year in byYear %}
                    <td>{{ year.female }}</td>
                {% endfor %}
            </tr>

            <tr>
                <td>всего:</td>
                {% for year in byYear %}
                    <td>{{ year.total }}</td>
                {% endfor %}
            </tr>
            </tbody>
        </table>
    </section>

    <section>
        <p>По национальностям</p>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>нац.</th>
                {% for nationality in byNationality %}
                    <th>{{ nationality.name }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>мальч.</td>
                {% for nationality in byNationality %}
                    <td>{{ nationality.male }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td>дев.</td>
                {% for nationality in byNationality %}
                    <td>{{ nationality.female }}</td>
                {% endfor %}
            </tr>
            <tr>
                <td>всего:</td>
                {% for nationality in byNationality %}
                    <td>{{ nationality.total }}</td>
                {% endfor %}
            </tr>
            </tbody>
        </table>
    </section>

{% endblock %}

src/Application/SchoolBundle/Resources/views/Report/create.html.twig
{% extends '::base.html.twig' %}
{% block content_title %}
    Создать отчет
{% endblock %}
{% block content %}
    {#{{ render(controller('ApplicationSchoolBundle:School:current')) }}#}
    <div class="jumbotron">
        {{ render(controller('ApplicationSchoolBundle:ClassGroup:getForm')) }}
    </div>
    <div class="report">
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('public/js/classgroup.js') }}"></script>
{% endblock %}

src/Application/SchoolBundle/Resources/views/Report/form.html.twig
{{ form_start(form,{'attr':{'class':'form-inline' }}) }}

{#{{ form_row(form.year) }}
    {{ form_row(form.submit) }}#}
{{ form_end(form) }}

src/Application/SchoolBundle/Resources/views/Report/index.html.twig
{% extends '::base.html.twig' %}
{% block content_title %}
    Панель отчета
{% endblock %}
{% block content %}
    {{ render(controller('ApplicationSchoolBundle:Report:searchForm')) }}
{% endblock %}