src/Application/SchoolBundle/Entity/ClassGroup.php
<?php

namespace Application\SchoolBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * ClassGroup
 */
class ClassGroup
{
    /**
     * @var integer
     */
    private $grade;

    /**
     * @var string
     */
    private $alphabet;

    /**
     * @var integer
     */
    private $id;

    /**
     * @var \Application\SchoolBundle\Entity\Personal
     */
    private $personal;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->students = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set grade
     *
     * @param integer $grade
     * @return ClassGroup
     */
    public function setGrade($grade)
    {
        $this->grade = $grade;

        return $this;
    }

    /**
     * Get grade
     *
     * @return integer
     */
    public function getGrade()
    {
        return $this->grade;
    }

    /**
     * Set alphabet
     *
     * @param string $alphabet
     * @return ClassGroup
     */
    public function setAlphabet($alphabet)
    {
        $this->alphabet = $alphabet;

        return $this;
    }

    /**
     * Get alphabet
     *
     * @return string
     */
    public function getAlphabet()
    {
        return $this->alphabet;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set personal
     *
     * @param \Application\SchoolBundle\Entity\Personal $personal
     * @return ClassGroup
     */
    public function setPersonal(\Application\SchoolBundle\Entity\Personal $personal = null)
    {
        $this->personal = $personal;

        return $this;
    }

    /**
     * Get personal
     *
     * @return \Application\SchoolBundle\Entity\Personal
     */
    public function getPersonal()
    {
        return $this->personal;
    }

    public function __toString()
    {
        return $this->getGrade() . '-' . $this->getAlphabet();
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $students;


    /**
     * Add students
     *
     * @param \Application\SchoolBundle\Entity\Student $students
     * @return ClassGroup
     */
    public function addStudent(\Application\SchoolBundle\Entity\Student $students)
    {
        $this->students[] = $students;

        return $this;
    }

    /**
     * Remove students
     *
     * @param \Application\SchoolBundle\Entity\Student $students
     */
    public function removeStudent(\Application\SchoolBundle\Entity\Student $students)
    {
        $this->students->removeElement($students);
    }

    /**
     * Get students
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStudents()
    {
        return $this->students;
    }

    public function getStudentsByEnd()
    {
        $count = 0;
        foreach ($this->students as $student) {
            if (is_object($student->getTransfer()) && $student->getTransfer()->getMoved() == 'Выбыл') {
                $count++;
            }
        }

        return $this->students->count() - $count;
    }

    public function getGenderCount()
    {
        $count = array('m' => 0, 'f' => 0);
        foreach ($this->students as $s) {
            $count['m'] += ($s->getSex() === 'М');
            $count['f'] += ($s->getSex() === 'Ж');
        }

        return $count;
    }

    public function getFull()
    {
        return $this->getGrade() . '-' . $this->getAlphabet();
    }

    /**
     * @var boolean
     */
    private $active;


    /**
     * Set active
     *
     * @param boolean $active
     * @return ClassGroup
     */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    /**
     * Get active
     *
     * @return boolean
     */
    public function getActive()
    {
        return $this->active;
    }
}

src/Application/SchoolBundle/Form/ClassGroupType.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 4/6/14
 * Time: 11:18 PM
 */

namespace Application\SchoolBundle\Form;


use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class ClassGroupType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('grade', 'entity',
            array(
                'class' => 'Application\SchoolBundle\Entity\ClassGroup',
                'query_builder' => function (EntityRepository $entityRepository) {
                        return $entityRepository->createQueryBuilder('g')
                            ->groupBy('g.grade')
                            ->orderBy('g.grade', 'ASC');
                    },
                'property' => 'grade',
                'translation_domain' => 'ApplicationSchoolBundle'))
            ->add('alphabet', 'entity',
                array(
                    'class' => 'Application\SchoolBundle\Entity\ClassGroup',
                    'query_builder' => function (EntityRepository $entityRepository) {
                            return $entityRepository->createQueryBuilder('a')
                                ->where('a.grade = 1')
                                ->orderBy('a.alphabet', 'ASC');
                        },
                    'property' => 'alphabet',
                    'label' => 'Серия',
                    'attr' => array('class' => 'form-control alphabet')
                ));
    }


    public function getName()
    {
        return 'school_class_group';
    }
}

src/Application/SchoolBundle/Controller/ClassGroupController.php
<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 02.04.14
 * Time: 12:26
 */

namespace Application\SchoolBundle\Controller;


use Application\SchoolBundle\Entity\ClassGroup;
use Application\SchoolBundle\Form\ClassGroupType;
use Doctrine\ORM\EntityNotFoundException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ClassGroupController extends Controller
{

    public function listAction()
    {
        $classGroups = $this->getDoctrine()->getRepository('ApplicationSchoolBundle:ClassGroup')->findAll();

        $paginator = $this->get('knp_paginator');

        $pagination = $paginator->paginate($classGroups, $this->get('request')->query->get('page', 1), 20);

        return $this->render('ApplicationSchoolBundle:ClassGroup:list.html.twig', array('classgroups' => $pagination));
    }

    public function getAction($id)
    {
        $classGroup = $this->getDoctrine()->getRepository('ApplicationSchoolBundle:ClassGroup')->find($id);

        return $this->render('@ApplicationSchool/ClassGroup/get.html.twig', array('classgroup' => $classGroup));
    }

    public function getFormAction()
    {
        $classGroup = new ClassGroup();
        $classForm = $this->createForm(
            new ClassGroupType(),
            $classGroup
        );
        return $this->render('ApplicationSchoolBundle:ClassGroup:form.html.twig', array('classForm' => $classForm->createView()));
    }

    public function alphabetAction($grade)
    {
        $classGroups = $this->getDoctrine()->getRepository('ApplicationSchoolBundle:ClassGroup')->findByGrade($grade);

        $data = $this->renderView('ApplicationSchoolBundle:ClassGroup:alphabet.html.twig', array('classGroups' => $classGroups));

        return new JsonResponse($data);
    }

    public function reportListAction(Request $request, $id, $type)
    {
        $classGroup = $this->getDoctrine()->getRepository('ApplicationSchoolBundle:ClassGroup')->find($id);

        if (!$classGroup) {
            throw new EntityNotFoundException();
        }

        $html = $this->renderView('@ApplicationSchool/ClassGroup/report_list.html.twig', array('class' => $classGroup));

        if ($request->isXmlHttpRequest()) {
            return new JsonResponse($html);
        } else if ($type == "pdf") {
            $mpdf = $this->get('tfox.mpdfport');
            $html = $this->renderView('@ApplicationSchool/ClassGroup/report_pdf.html.twig', array('class' => $classGroup));
            return $mpdf->generatePdfResponse($html);
        } else {
            $html = $this->renderView('@ApplicationSchool/ClassGroup/report_html.html.twig', array('class' => $classGroup));
            return new Response($html);
        }
    }

    public function classGroupAction(Request $request, $id, $type)
    {
        $em = $this->getDoctrine()->getManager();
        $classGroup = $em->getRepository('ApplicationSchoolBundle:ClassGroup')->find($id);

        //TODO: Should select default school
        $school = $em->getRepository('ApplicationSchoolBundle:School')->findAll()[0];

        if (!$classGroup) {
            throw new EntityNotFoundException();
        }

        $byYear = $em->getRepository('ApplicationSchoolBundle:Student')->byYear($classGroup);

        $byNationality = $em->getRepository('ApplicationSchoolBundle:Student')->byNationality($classGroup);


        $html = $this->renderView('ApplicationSchoolBundle:Report:classgroup.html.twig', array('classgroup' => $classGroup, 'byYear' => $byYear, 'school' => $school, 'byNationality' => $byNationality));

        if ($request->isXmlHttpRequest())
            return new JsonResponse($html);
        else if ($type == "pdf") {
            $mpdf = $this->get('tfox.mpdfport');
            return $mpdf->generatePdfResponse($html);
        } else
            return new Response($html);
    }
} 

src/Application/SchoolBundle/Resources/views/ClassGroup/alphabet.html.twig
<select class="form-control alphabet" required="required" name="school_class_group[alphabet]"
        id="school_class_group_alphabet">
    {% for c in classGroups %}
        <option value="{{ c.id }}">{{ c.alphabet }}</option>
    {% endfor %}
    </select>

src/Application/SchoolBundle/Resources/views/ClassGroup/form.html.twig
{{ form_start(classForm) }}
{{ form_row(classForm.grade) }}
{{ form_row(classForm.alphabet) }}
<div class="form-group">
    <fieldset>
        <legend>Выберите тип отчета</legend>
        <label class="btn-radio">
            <input type="radio" name="type" value="report" checked>
            <span>Отчет</span>
        </label>
        <label class="btn-radio">
            <input type="radio" name="type" value="list">
            <span>Список учащихся</span>
        </label>
    </fieldset>
</div>
<div class="form-group">
    <input type="button" class="form-control btn btn-primary btn-report" value="Получить отчет">
</div>

{{ form_end(classForm) }}

src/Application/SchoolBundle/Resources/views/ClassGroup/get.html.twig
{% extends '::base.html.twig' %}
{% block content %}
    <h5>Список учащихся <strong>{{ classgroup.grade }} "{{ classgroup.alphabet }}"</strong> класса <span
                class="pull-right">Классный руководитель <strong>{{ classgroup.personal.lastname }} {{ classgroup.personal.firstname }}</strong></span>
    </h5>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>№</th>
            <th>Ф.И. ученика</th>
            <th>№ л.дела</th>
            <th>Пол</th>
            <th>Нац.</th>
            <th>Год рождения</th>
            <th>Адрес</th>
            <th>Телефон</th>
            <th>Прибыл</th>
            <th>Выбыл</th>
            <th>Число(выбыл)</th>
        </tr>
        </thead>
        <tbody>
        {% for s in classgroup.students %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ s.lastname }} {{ s.firstname }}</td>
                <td>{{ s.personalNumber }}</td>
                <td>{{ s.sex }}</td>
                <td>{{ s.nationality }}</td>
                <td>{{ s.birthday|date('d-m-Y') }}</td>
                <td>{{ s.address }}</td>
                <td>{{ s.telephone }}</td>
                <td>{% if s.transfer and s.transfer.moved =='Выбыл' %} {{ s.transfer }} {% endif %}</td>
                <td>{% if s.transfer and s.transfer.moved =='Прибыл' %} {{ s.transfer }} {% endif %}</td>
                <td>{% if s.transfer and s.transfer.moved =='Прибыл' %} {{ s.transfer.date|date('d-m-Y') }} {% endif %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p> Мальчиков: <strong>{{ classgroup.genderCount.m }}</strong></p>
    <p>Девочек: <strong>{{ classgroup.genderCount.f }}</strong></p>


{% endblock %}

src/Application/SchoolBundle/Resources/views/ClassGroup/list.html.twig
{% extends '::base.html.twig' %}
{% block content_title %}
    Мониторинг движения учащихся по классам
    <input type="button" class="btn btn-warning pull-right" value="Добавить в архив">
{% endblock %}
{% block content %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th>№</th>
            <th>Класс</th>
            <th>Руководитель класса</th>
            <th>Список учащихся</th>
            <th>Отчет по движению учащихся</th>
        </tr>
        </thead>
        {% for classgroup in classgroups %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ classgroup.grade }} - {{ classgroup.alphabet }}</td>
                <td>{{ classgroup.personal }}</td>
                <td>
                    <a class="text-success" href="{{ path('classgroup_report_list',{'id': classgroup.id}) }}">Подробная
                        информация</a>
                    <a href="{{ path('classgroup_report_list',{'id':classgroup.id, 'type':'pdf'}) }}">В PDF формат</a>
                </td>
                <td>
                    <a class="text-success" href="{{ path('classgroup_report_classgroup',{'id': classgroup.id}) }}">
                        Просмотреть отчет по классу
                    </a>
                    <a href="{{ path('classgroup_report_classgroup',{'id':classgroup.id, 'type':'pdf'}) }}">В PDF
                        формат</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    {{ knp_pagination_render(classgroups) }}
{% endblock %}

src/Application/SchoolBundle/Resources/views/ClassGroup/report_html.html.twig
{% extends '::base.html.twig' %}
{% block content %}
    {{ include('@ApplicationSchool/ClassGroup/report_list.html.twig') }}
{% endblock %}

src/Application/SchoolBundle/Resources/views/ClassGroup/report_list.html.twig
<h5>Список учащихся <strong>{{ class.grade }} "{{ class.alphabet }}"</strong> класса <span class="pull-right">Классный руководитель <strong>{{ class.personal.lastname }} {{ class.personal.firstname }}</strong></span>
</h5>
<table class="table table-bordered table-striped">
<thead>
    <tr>
        <th>№</th>
        <th>Ф.И. ученика</th>
        <th>№ л.дела</th>
        <th>Пол</th>
        <th>Нац.</th>
        <th>Год рождения</th>
        <th>Адрес</th>
        <th>Телефон</th>
        <th>Прибыл</th>
        <th>Выбыл</th>
        <th>Число(выбыл)</th>
    </tr>
    </thead>
    <tbody>
    {% for s in class.students %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ s.lastname }} {{ s.firstname }}</td>
            <td>{{ s.personalNumber }}</td>
            <td>{{ s.sex }}</td>
            <td>{{ s.nationality }}</td>
            <td>{{ s.birthday|date('d-m-Y') }}</td>
            <td>{{ s.address }}</td>
            <td>{{ s.telephone }}</td>
            <td>{% if s.transfer and s.transfer.moved =='Выбыл' %} {{ s.transfer }} {% endif %}</td>
            <td>{% if s.transfer and s.transfer.moved =='Прибыл' %} {{ s.transfer }} {% endif %}</td>
            <td>{% if s.transfer and s.transfer.moved =='Прибыл' %} {{ s.transfer.date|date('d-m-Y') }} {% endif %}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<p> Мальчиков: <strong>{{ class.genderCount.m }}</strong></p>
<p>Девочек: <strong>{{ class.genderCount.f }}</strong></p>

src/Application/SchoolBundle/Resources/views/ClassGroup/report_pdf.html.twig
{% extends 'ApplicationSchoolBundle::layout.html.twig' %}
{% block content %}
    {{ include('@ApplicationSchool/ClassGroup/report_list.html.twig') }}
{% endblock %}